# Сервер отправки лога с РТК
[server]
url = http://172.21.240.121:9090/applications/ERP-exchange/api/rtk/log
username = ad1mzIGwAeYJ7NOLnQIsdhLBuQO3QSA4M1qs0xugwys=
password = Ef7FjxOVGwELnrMiOwbntbhlGeBWbilRwg7mw1XFNog=
url_token = http://172.21.240.121:9090/applications/ERP-exchange/sys/token

# Запрос заказов
[serverOrder]
getOrders_url = https://c.prosyst.ru/prosoft_erp_work/hs/rtk/orderlist/RTK_R050_BoardsIO_1
password = Basic cnRrX2NtcHA6NDU2Nzg5QWE=
fetch_data_url = https://c.prosyst.ru/prosoft_erp_work/hs/rtk/order/RTK_R050_BoardsIO_1/%D0%97%D0%9D%D0%9F-

# Пордтверждение плат
[checkboard]
checkboardurl = https://c.prosyst.ru/prosoft_erp_work/hs/rtk
username = rtk_cmpp
password = 456789Aa